* Theme variables
:PROPERTIES:
:CUSTOM_ID: theme-variables
:END:
This theme can be tweaked using the following =[Params]= variables in
=config.toml=.

#+BEGIN_EXAMPLE
[Params]
  tagline = "My random notes"

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  # https://github.com/poole/lanyon#themes
  themecolorbase = "8" # Valid values: "8", "9", "a", "b", "c", "d", "e", "f"

  defaultsection = "posts" # Use in Refined theme (layouts/_default/rss.xml)
#+END_EXAMPLE
** Isso comment support
:PROPERTIES:
:CUSTOM_ID: isso-comment-support
:END:
To enable the Isso comment block, the =.Site.Params.isso= block needs to be
present.
- =.Site.Params.isso.server= -- This is a mandatory variable. It must match the
  =[server] > listen= variable set in the =isso.conf= file (See [[https://posativ.org/isso/docs/configuration/server/][Isso Server
  Configuration]]).
- =.Site.Params.isso.hidenamefield= -- Presence of this variable will hide the
  Name field.
- =.Site.Params.isso.hideemailfield= -- Presence of this variable will hide the
  Email field.
- =.Site.Params.isso.hidewebsitefield= -- Presence of this variable will hide the
  Website field.
- =.Site.Params.isso.tagline= -- This is an HTML string which is appended at the
  end of the Isso comment thread. Below example gives an idea of how this can be
  used.
#+BEGIN_EXAMPLE
[Params]
  [Params.isso] # Presence of .Site.Params.isso will enable Isso comments
    server = "localhost:1234" # Mandatory variable
    # hidenamefield = true # uncomment this line to hide the Name field
    # hideemailfield = true # uncomment this line to hide the Email field
    # hidewebsitefield = true # uncomment this line to hide the Website field
    tagline = """
            <p><small>Formatting Tips&mdash;
                      <b>**bold**</b>,
                      <i>*italics*</i>,
                      <code>`monospace`</code>,
                      <code>```</code>&#92;nmulti-line&#92;ncode&#92;n<code>```</code>
            </small></p>"""
#+END_EXAMPLE
** Remarkbox comment support
:PROPERTIES:
:CUSTOM_ID: remarkbox-comment-support
:END:
To enable the Remarkbox comment block, the =.Site.Params.remarkbox= block needs
to be present.

- =.Site.Params.remarkbox.owner_key= -- This is a mandatory variable. Enter your
  Remarkbox =rb_owner_key= value here.
#+BEGIN_EXAMPLE
[Params]
  [Params.remarkbox] # Presence of .Site.Params.remarkbox will enable Remarkbox comments
    owner_key = "fmcwgrsa-qlym-gces-bkkv-srvpfjsutwhg" # random keys used here for example
#+END_EXAMPLE
*** Useful CSS for the Remarkbox iframe
Add the below to /Custom stylesheet/ on =https://my.remarkbox.com/ns/YOUR-NAMESPACE/settings=.
#+BEGIN_SRC css
/* Reduce the comment box height */
.common-textarea {
    height: 40px;
}

/* Reduce the empty space below the "save message" button */
body > .main {
    height: 160px;
}

/* Hide the default centered Remarkbox tag */
body > .main > center {
    display: none;
}

/* Hide the default centered Remarkbox logo */
#remarkbox-footer {
    display: none;
}
#+END_SRC
